version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - keycloak

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - keycloak

  keycloak:
    build: ./keycloak
    ports:
      - "8080:8080"

  maxscale:
    build: ./maxscale
    ports:
      - "3306:3306"
    depends_on:
      - backend
