version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - keycloak
      - maxscale
    environment:
      - DATABASE_HOST=maxscale
      - DATABASE_USER=root
      - DATABASE_PASSWORD=my-secret-pw
      - DATABASE_NAME=backend_db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - keycloak

  keycloak:
    image: dhet/cloakmail-keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=mariadb
      - DB_ADDR=mariadb
      - DB_DATABASE=keycloak
      - DB_USER=root
      - DB_PASSWORD=my-secret-pw
    command: ["start-dev"]
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.5
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=keycloak
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d

  maxscale:
    image: mariadb/maxscale
    ports:
      - "3308:3306"
    volumes:
      - ./maxscale/maxscale.cnf:/etc/maxscale.cnf
      - ./maxscale/rsyslog.conf:/etc/rsyslog.conf
    depends_on:
      - mariadb
